CREATE TABLE IF NOT EXISTS `jawaban_user` (
  `id_jawaban_user` int(11) NOT NULL AUTO_INCREMENT,
  `id_user` int(11) NOT NULL,
  `id_jadwal_test` int(11) NOT NULL,
  `id_form_soal` int(11) NOT NULL,
  `id_soal` int(11) NOT NULL,
  `id_jawaban_soal` int(11) DEFAULT NULL,
  `waktu_jawab` datetime NOT NULL,
  `is_ragu` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_jawaban_user`),
  KEY `id_jadwal_test` (`id_jadwal_test`),
  KEY `id_form_soal` (`id_form_soal`),
  KEY `id_soal` (`id_soal`),
  KEY `id_jawaban` (`id_jawaban_soal`),
  KEY `id_user` (`id_user`),
  CONSTRAINT `jawaban_user_ibfk_1` FOREIGN KEY (`id_jadwal_test`) REFERENCES `jadwal_test` (`id_jadwal_test`),
  CONSTRAINT `jawaban_user_ibfk_2` FOREIGN KEY (`id_form_soal`) REFERENCES `form_soal` (`id_form_soal`),
  CONSTRAINT `jawaban_user_ibfk_3` FOREIGN KEY (`id_soal`) REFERENCES `soal` (`id_soal`),
  CONSTRAINT `jawaban_user_ibfk_4` FOREIGN KEY (`id_jawaban_soal`) REFERENCES `jawaban_soal` (`id_jawaban_soal`),
  CONSTRAINT `jawaban_user_ibfk_5` FOREIGN KEY (`id_user`) REFERENCES `user` (`id_user`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
